import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
  await knex("words").del();
  const list = [
    "apple",
    "banana",
    "house",
    "cat",
    "dog",
    "car",
    "bicycle",
    "tree",
    "sun",
    "moon",
    "star",
    "book",
    "phone",
    "computer",
    "keyboard",
    "guitar",
    "pizza",
    "cake",
    "ball",
    "river",
    "mountain",
    "castle",
    "robot",
    "rocket",
    "dragon",
    "island",
    "umbrella",
    "elephant",
    "penguin",
    "butterfly",
    "sandwich",
    "volcano",
    "rainbow",
    "skateboard",
    "lighthouse",
    "snowman",
    "campfire",
    "waterfall",
    "spider",
    "helicopter",
    "octopus",
    "dinosaur",
    "sunglasses",
    "backpack",
    "microphone",
    "toothbrush",
    "jellyfish",
    "kangaroo",
    "windmill",
    "telescope",
    "pumpkin",
  ];
  await knex("words").insert(list.map((w) => ({ word: w })));
}
